---
- name: "Variable configuration."
  include_tasks: variables.yml

- name: "Uninstall MySQL server."
  include_tasks: uninstall.yml
  when: state|default('present') == "absent"

- name: "Setup/install tasks."
  include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' and state|default('present') == "present"

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian' and state|default('present') == "present"

- include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux' and state|default('present') == "present"

- name: "Check if MySQL packages were installed."
  set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed)
      or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed)
      or (arch_mysql_install_packages is defined and arch_mysql_install_packages.changed) }}"

- name: "Configure MySQL."
  include_tasks: configure.yml
  when: state|default('present') == "present"

- name: "Secure installation"
  include_tasks: secure-installation.yml
  when: state|default('present') == "present"

- name: "Create databases"
  include_tasks: databases.yml
  when: state|default('present') == "present"

- name: "Create users"
  include_tasks: users.yml
  when: state|default('present') == "present"

- name: "Setup replication"
  include_tasks: replication.yml
  when: state|default('present') == "present"
